version: '3.7'
services:
  rclone-gdrive:
    image: rclone/rclone:1.57.0
    container_name: rclone-gdrive
    user: root
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - "apparmor:unconfined"
    environment:
      - RCLONE_ALLOW_OTHER=true
      - RCLONE_VERBOSE=2
      - TZ=${TZ}
    volumes:
      - ./${RCLONE_FOLDER}:/config/rclone
      - type: bind
        source: ./${RCLONE_DATA_FOLDER}
        target: /mnt
        bind:
          propagation: shared
    command: ['mount','--allow-non-empty','gdrive:','/mnt']
    restart: always

#  docker run --rm -it --volume RCLONE_FOLDER:/config/rclone --volume DATA_FOLDER:/data --user $(id -u):$(id -g) rclone/rclone config

  rclone-onedrive:
    image: rclone/rclone
    container_name: rclone-onedrive
    user: root
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - "apparmor:unconfined"
    environment:
      - RCLONE_ALLOW_OTHER=true
      - RCLONE_VERBOSE=2
      - TZ=${TZ}
    volumes:
      - ./${RCLONE_ONEDRIVE_FOLDER}:/config/rclone
      - type: bind
        source: ./${RCLONE_ONEDRIVE_DATA_FOLDER}
        target: /mnt
        bind:
          propagation: shared
    command: ['mount','--allow-non-empty','onedrive:','/mnt']
    restart: always
