version: '3.7'
services:
  posteio:
    image: analogic/poste.io:latest
    container_name: poste.io
    hostname: ${MAIL_HOSTNAME}
    environment:
      - HOSTNAME=${MAIL_HOSTNAME_SUBDOMAIN}
      - HTTPS=ON
      - DISABLE_CLAMAV=TRUE
      - VIRTUAL_HOST=${MAIL_VIRTUAL_HOST}
    ports:
      - '25:25'    # SMTPS - mostly processing incoming mails
      - '465:465'  # SMTPS - mostly processing incoming mails
      - '80:80'    # HTTP - access to administration or webmail client
      - '110:110'  #  POP3 - standard protocol for accessing mailbox, STARTTLS is required before client auth                                                                                             >
      - '143:143'  #  IMAP - standard protocol for accessing mailbox, STARTTLS is required before client auth
      - '443:443' #  HTTPS - access to administration or webmail client
      - '587:587'  #  MSA - SMTP port used primarily for email clients after STARTTLS and auth
      - '993:993'  #  IMAPS - alternative port for IMAP encrypted since connection
      - '995:995'  #  POP3S - encrypted POP3 since connections
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./${MAIL_FOLDER}/data:/data
    restart: always
